goal_reached:
  reward: 17.5

safe_dist:
  punishment: 0.05

collision:
  punishment: 10

goal_approached:
  reward_factor: 0.4
  penalty_factor: 0.5

reverse_drive:
  penalty: 0.00001

distance_global_plan:
  reward_factor: 0.1
  penalty_factor: 0.15

abrupt_vel_change:
  "0":
    vel_idx: 0
    factor: 0.25

  "-1":
    vel_idx: -1
    factor: 0.05

  "1":
    vel_idx: 1
    factor: 0.05