contestants:

  - name: teb-sideways
    local_planner: teb
    inter_planner: sideways

  - name: teb-basic
    local_planner: teb
    inter_planner: sideways

  - name: teb-aggressive
    local_planner: teb
    inter_planner: aggressive