DYNAMICMAP: {}
PARAMETRIZED:
  file: default.xml
RANDOM:
  dynamic:
    max: 5
    min: 3
    models:
    - actor1
  interactive:
    max: 0
    min: 0
    models:
    - shelf
  static:
    max: 10
    min: 5
    models:
    - shelf
SCENARIO:
  file: default.json
STAGED:
  curriculum: default.yaml
  index: 0
autoreset: true
episodes: 50
