PARAMETRIZED:
  file: default.xml
RANDOM:
  dynamic:
    max: 5
    min: 3
    models:
    - actor1
  interactive:
    max: 0
    min: 0
    models:
    - shelf
  seed: 2019047987
  static:
    max: 10
    min: 5
    models:
    - shelf
SCENARIO:
  file: arena_hospital_small_4.json
STAGED:
  curriculum: default.yaml
  index: 0
episodes: -1
