episodes: 50

SCENARIO:
  file: default.json

PARAMETRIZED:
  file: default.xml 

STAGED:
  curriculum: "default.yaml"
  index: 0

DYNAMICMAP: {}

RANDOM:
  seed: -1
  static:
    min: 4
    max: 4
    models: ["shelf"]
  interactive:
    min: 0
    max: 0
    models: ["shelf"]
  dynamic:
    min: 4
    max: 4
    models: ["actor1"]
