# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

# Training Curriculum 
# this yaml serves as container of the learning curriculum for the agent
# by determining the number of static/dynamic obstacles per stage
# (will carry on training on last stage when threshhold reached)

- #0
  goal_radius: 1.5
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.00
      smooth_iter: 1
    # rosnav:
    #   map_type: indoor
    #   indoor:
    #     corridor_radius: 5
    #     iterations: 100
    #   outdoor:
    #     obstacle_num: 5
    #     obstacle_extra_radius: 1
  static: 0
  dynamic: 5
- #1
  goal_radius: 1.0
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.05
      smooth_iter: 1
  static: 0
  dynamic: 5
- #2
  goal_radius: 0.75
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.05
      smooth_iter: 1
  static: 0
  dynamic: 10
- #3
  goal_radius: 0.3
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.10
      smooth_iter: 1
    barn:
      fill_pct: 0.1
      smooth_iter: 2

  static: 0
  dynamic: 15
- #4
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.125
      smooth_iter: 2
  static: 0
  dynamic: 20
- #5
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.15
      smooth_iter: 2
  static: 0
  dynamic: 30
- #6
  map_generator:
    algorithm: "barn"
    algorithm_config:
      fill_pct: 0.175
      smooth_iter: 3
  static: 0
  dynamic: 40